### ISSUE TITLE
pyproj and owslib to be removed from the depencies?

### ISSUE THREAD

**Issue by maximlt** [CS-SI/eodag#309]
Since the CSWSearch plugin isn't used by EODAG as WEKEO isn't supported.

**Comment by sbrunato** [comment]
This is related to:
- #104: because a QGIS plugin may crash due to these dependencies, see https://github.com/qgis/QGIS-Enhancement-Proposals/issues/202#issuecomment-787512133
- #94 and #15, because even if CSWSearch plugin is not used for the moment, some other providers like CEDA may need it in the future.

What can be done for the moment is to temporally remove these dependencies and the CSWSearch plugin, as the QGIS plugin should be a great feature.

And if we decide to support CEDA, or another provider using CSW, then we should update the CSWSearch plugin to make it work with QGIS.

**Comment by sbrunato** [comment]
`pyproj` was removed from `OWSLib >=0.27.1` dependencies, and also from eodag in #1021
