### ISSUE TITLE
results of search with product id is empty with creodias provider

### ISSUE THREAD

**Issue by savmickael** [CS-SI/eodag#325]
**Describe the bug**
the following code return a empty search result: 
``` python
dag = EODataAccessGateway(config_file)
dag.set_preferred_provider('creodias')
products,_ = dag.search(id=product_id,provider='creodias')
```
with `product_id=S1A_IW_GRDH_1SDV_20210202T060100_20210202T060125_036407_0445F3_EDB8`

Nevertheless the logging indicates that eodag found 2 products. Result confirmd trough the creodias finder.

**Environment:**
 - Python version: 3.6
 - EODAG version: 2.2

**Additional context**
Linked to WordlCereal project

**Comment by sbrunato** [comment]
The problem here is caused by the fact that creodias returns [2 results](https://finder.creodias.eu/resto/api/collections/Sentinel1/search.json?productIdentifier=%S1A_IW_GRDH_1SDV_20210202T060100_20210202T060125_036407_0445F3_EDB8%) for this query: 
`f"{product_id}.SAFE"` and `f"{product_id}_CARD_BS"`. 

And if a search-by-id gets a number of results `!= 1`, it will return an empty search result.

- [ ] We need to find a way to handle this scenario
