### ISSUE TITLE
remote_location and "storageStatus" Not available for Mundi

### ISSUE THREAD

**Issue by harshal306** [CS-SI/eodag#441]
**Mundi provider failed to download EOProduct**

*requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mundiwebservices.com/dp/?prefix=Not%20Available*

While Downloading the EOProduct for Mundi provider. The product does not have remote_location available. Moreover, storageStatus shows None.

**Sample Script**

```py
from eodag import EODataAccessGateway
dag = EODataAccessGateway()
result = dag.search(productType="S2_MSI_L2A", start="2022-01-01",end="2022-03-24")
print(f"Remote Location- {result[0].remote_location}")
print(f"storageStatus- {result[0].properties.get('storageStatus')}")
```

**Output**
Remote Location- Not Available
storageStatus- None

**Environment:**
 - Python version: `Python 3.8.12`
 - EODAG version: `eodag (Earth Observation Data Access Gateway): version 2.4.0`

**Comment by sbrunato** [comment]
Hello @harshal306 , and thanks for submitting this issue.

This error seems to be caused by different products delivery formats that we did not notice until now:
- in https://mundiwebservices.com/acdc/catalog/proxy/search/Sentinel2/opensearch?uid=S2B_MSIL2A_20220102T104339_N0301_R008_T31TDJ_20220102T122433 we can find `<DIAS:productDeliveryFormat>folder</DIAS:productDeliveryFormat>` which is the entry eodag is configured for
- and in https://mundiwebservices.com/acdc/catalog/proxy/search/Sentinel2/opensearch?uid=S2B_MSIL2A_20220101T000459_N0301_R130_T53DMB_20220101T012649 like in your example, we find `<DIAS:productDeliveryFormat>zip</DIAS:productDeliveryFormat>` and in this case, the information we need for download is missing

I am going to investigate and maybe contact mundi helpdesk to find how to hanfle it. I'll keep you informed

**Comment by harshal306** [comment]
Thanks, @sbrunato for the consideration.
The same issue is with the Sentinel-1 data. EOProduct is found in the search criteria like yours but the download information is missing.

Looking forward to keeping myself in the loop.
